tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "aws/tap"
tap "golangci/tap"
tap "goreleaser/tap"
tap "iann0036/iamlive"
tap "romkatv/powerlevel10k"
tap "warrensbox/tap"

brew "arkade"
brew "ansible"
brew "awscli"
brew "bash"
brew "bat"
brew "bazaar"
brew "dasel"
brew "dfu-util"
brew "docker-compose"
brew "docker-machine"
brew "dockutil"
brew "dos2unix"
brew "fd"
brew "gettext"
brew "git"
brew "openjdk"
brew "git-credential-manager"
brew "go"
brew "groovy"
brew "helm"
brew "httpie"
brew "hugo"
brew "istioctl"
brew "jq"
brew "jump"
brew "kubernetes-cli"
brew "kops"
brew "kubectx"
brew "k3d"
brew "k3sup"
brew "linkerd"
brew "mas"
brew "md5sha1sum"
brew "mercurial"
brew "nvm"
brew "packer"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rustup-init"
brew "shellcheck"
brew "travis"
brew "tree"
brew "wget"
brew "yamllint"
brew "yq"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

brew "golangci/tap/golangci-lint"
brew "goreleaser/tap/goreleaser"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "warrensbox/tap/tfswitch"
brew "warrensbox/tap/tgswitch"

cask "balenaetcher"

cask "logitech-camera-settings"
cask "logitech-options"

cask "grammarly"
cask "istat-menus"
cask "shiftit"
cask "vlc"
cask "spotify"
cask "the-unarchiver"

cask "arduino"
cask "easyeda"
cask "diffmerge"
cask "rancher"
cask "docker"
cask "intellij-idea-ce"
cask "visual-studio-code"

cask "iterm2"
cask "lens"
cask "ngrok"
cask "paw"
cask "sourcetree"
cask "vmware-fusion"

cask "discord"
cask "keybase"
cask "slack-beta"

cask "brave-browser"
cask "firefox-developer-edition"
cask "google-chrome-canary"
cask "opera-developer"
cask "tor-browser"

cask "bluejeans"
cask "zoom"

cask "grammarly"

mas "Grammarly for Safari", id: 1462114288
